# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Edmund Mills
description: >- # this means to ignore newlines until "baseurl:"
  Writing about Machine Learning and AI alignment
baseurl: "" # the subpath of your site, e.g. /blog
url: 'https://www.edmundmills.com/'
github_username:  edmundmills

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

title: 'Edmund Mills'
name: 'Edmund Mills'
minimal_mistakes_skin: "mint"
locale: "en-US"
paginate: 5
site:
 - description: AI Alignment Research

repository: "edmundmills/blog"

search: true

author:
  name: "Edmund Mills"
  avatar: "assets/images/favicons/android-chrome-384x384.png"
  bio: "AI Alignment Reseach" # Note: Markdown is allowed
  location: "Bay Area, CA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/edmundmills"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/edmundmmills"
    - label: "Google Scholar"
      icon: "ai ai-fw ai-google-scholar-square"
      url: "https://scholar.google.com/citations?hl=en&user=djelh-cAAAAJ&view_op=list_works"

include: ["_pages"]

collections:
  personal_writing:
    output: false
    permalink: /:collection/:path
  climate_kindness:
    output: true
    permalink: /:collection/:path
  machine_learning:
    output: true
    permalink: /machine_learning/:path
  portfolio:
    output: false
    permalink: /:collection/:path

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      show_date: true
      classes: wide
      author_profile: true


defaults:
  # _climate_kindness
  - scope:
      path: ""
      type: climate_kindness
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      classes: wide
      header:
        # show_overlay_excerpt: false
        overlay_filter: 0.5

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/edmundmills"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/edmundmmills"
    - label: "Google Scholar"
      icon: "ai ai-fw ai-google-scholar-square"
      url: "https://scholar.google.com/citations?hl=en&user=djelh-cAAAAJ&view_op=list_works"


responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 1024

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment